# SEO Values
title: SmoothOperator
tagline: (Marshall Peck)
description: a resume, a portfolio... all on one page!
url: https://smoothoperator.github.io/
twitter: https://twitter.com/zenorocha
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: SmoothOperator
  owner_url: https://github.com/SmoothOperator
  repository_url: https://github.com/SmoothOperator/smoothoperator.github.io

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
