# SEO Values
title: My Awesome Portfolio
tagline: Showcasing my best projects and designs
description: This is the portfolio of Mars, featuring a collection of creative and technical projects.
url: https://smoothoperator.github.io/
twitter: https://twitter.com/your_twitter_handle
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics: UA-XXXXXXXXX-X

# GitHub Values
github:
  owner_name: SmoothOperator
  owner_url: https://github.com/SmoothOperator
  repository_url: https://github.com/SmoothOperator/smoothoperator.github.io

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
